// This file is generated by `npm run build:atlas`.
// It is safe to keep this empty before real sprite sheets are added.

export const GeneratedAtlases = {} as const;

export const GeneratedIconFrames = {} as const;

export const GeneratedAssetPacks: ReadonlyArray<{
  key: string;
  imagePath: string;
  atlasPath: string;
}> = [];
