// This file is generated by `npm run build:atlas`.
// Do not edit by hand. Edit tools/asset-sheets.config.json instead.

export const GeneratedAtlases = {} as const;

export const GeneratedIconFrames = {} as const;

export const GeneratedAssetPacks: ReadonlyArray<{
  key: string;
  imagePath: string;
  atlasPath: string;
}> = [];
