export const SodaIconAtlases = {
  SodaIcons: 'soda-icons',
} as const;

export const SodaIconFrames = {
  // Materials
  MaterialsAntler: 'materials/antler.png',
  MaterialsBar2: 'materials/bar2.png',
  MaterialsBrick: 'materials/brick.png',
  MaterialsCoins: 'materials/coins.png',
  MaterialsCoral: 'materials/coral.png',
  MaterialsFeather: 'materials/feather.png',
  MaterialsFur: 'materials/fur.png',
  MaterialsGem1: 'materials/gem1.png',
  MaterialsGem2: 'materials/gem2.png',
  MaterialsGem3: 'materials/gem3.png',
  MaterialsGem4: 'materials/gem4.png',
  MaterialsGem5: 'materials/gem5.png',
  MaterialsGravel: 'materials/gravel.png',
  MaterialsHorn2: 'materials/horn2.png',
  MaterialsLeatherRoll: 'materials/leatherroll.png',
  MaterialsRock: 'materials/rock.png',
  MaterialsShell: 'materials/shell.png',
  MaterialsSkull: 'materials/skull.png',
  MaterialsString: 'materials/string.png',
  MaterialsTooth: 'materials/tooth.png',
  MaterialsWood: 'materials/wood.png',
  MaterialsWool: 'materials/wool.png',

  // Potions & Herbs
  PotionHerbsHerb1: 'potions_herbs/herb1.png',
  PotionHerbsHerb2: 'potions_herbs/herb2.png',
  PotionHerbsHerb3: 'potions_herbs/herb3.png',
  PotionHerbsHerb4: 'potions_herbs/herb4.png',
  PotionHerbsHerb5: 'potions_herbs/herb5.png',
  PotionHerbsPotionBlue: 'potions_herbs/potion-blue.png',
  PotionHerbsPotionLightGreen: 'potions_herbs/potion-lightgreen.png',
  PotionHerbsPotionPurple: 'potions_herbs/potion-purple.png',
  PotionHerbsPotionRed: 'potions_herbs/potion-red.png',
  PotionHerbsPotionYellow: 'potions_herbs/potion-yellow.png',

  // System & Misc
  SystemMiscBook: 'system_misc/misc-book.png',
  SystemMiscBronzeStar: 'system_misc/misc-bronzestar.png',
  SystemMiscCog: 'system_misc/misc-cog.png',
  SystemMiscDark: 'system_misc/misc-dark.png',
  SystemMiscDownArrow: 'system_misc/misc-downarrow.png',
  SystemMiscElectric: 'system_misc/misc-electric.png',
  SystemMiscFire: 'system_misc/misc-fire.png',
  SystemMiscFist: 'system_misc/misc-fist.png',
  SystemMiscFullHeart: 'system_misc/misc-fullheart.png',
  SystemMiscGoldStar: 'system_misc/misc-goldstar.png',
  SystemMiscHalfHeartLeft: 'system_misc/misc-halfheartleft.png',
  SystemMiscHalfHeartRight: 'system_misc/misc-halfheartright.png',
  SystemMiscHolyIcon: 'system_misc/misc-holyicon.png',
  SystemMiscIce: 'system_misc/misc-ice.png',
  SystemMiscImpact: 'system_misc/misc-impact.png',
  SystemMiscLightIcon: 'system_misc/misc-lighticon.png',
  SystemMiscMusicNote: 'system_misc/misc-musicnote.png',
  SystemMiscNature: 'system_misc/misc-nature.png',
  SystemMiscRock: 'system_misc/misc-rock.png',
  SystemMiscRun: 'system_misc/misc-run.png',
  SystemMiscShield: 'system_misc/misc-shield.png',
  SystemMiscSilverStar: 'system_misc/misc-silverstar.png',
  SystemMiscStrike: 'system_misc/misc-strike.png',
  SystemMiscUpArrow: 'system_misc/misc-uparrow.png',
  SystemMiscWater: 'system_misc/misc-water.png',

  // Food
  FoodApple: 'food/apple.png',
  FoodBread: 'food/bread.png',
  FoodCabbage: 'food/cabbage.png',
  FoodCarrot: 'food/carrot.png',
  FoodCheese: 'food/cheese.png',
  FoodCherries: 'food/cherries.png',
  FoodCupOfTea: 'food/cupoftea.png',
  FoodEgg: 'food/egg.png',
  FoodFish: 'food/fish.png',
  FoodGrapes: 'food/grapes.png',
  FoodGrapes2: 'food/grapes2.png',
  FoodHerbRoot: 'food/herbroot.png',
  FoodHotSauce: 'food/hotsauce.png',
  FoodMonsterEgg: 'food/monsteregg.png',
  FoodMushroom: 'food/mushroom.png',
  FoodOnion: 'food/onion.png',
  FoodOrange: 'food/orange.png',
  FoodPaperBag: 'food/paperbag.png',
  FoodPeach: 'food/peach.png',
  FoodPeanut: 'food/peanut.png',
  FoodRedPepper: 'food/redpepper.png',
  FoodSalt: 'food/salt.png',
  FoodSausage: 'food/sausage.png',
  FoodTomato: 'food/tomato.png',
  FoodTurnip: 'food/turnip.png',

  // Instruments
  InstrumentsBell: 'instruments/bell.png',
  InstrumentsDrum: 'instruments/drum.png',
  InstrumentsFlute: 'instruments/flute.png',
  InstrumentsHarp: 'instruments/harp.png',
  InstrumentsHorn: 'instruments/horn.png',
  InstrumentsLute: 'instruments/lute.png',
  InstrumentsMusicBox: 'instruments/musicbox.png',
  InstrumentsOcarina: 'instruments/ocarina.png',

  // Weapons
  WeaponsAxe: 'weapons/axe.png',
  WeaponsBattleAxe: 'weapons/battleaxe.png',
  WeaponsBow: 'weapons/bow.png',
  WeaponsChainsaw: 'weapons/chainsaw.png',
  WeaponsChainWhip: 'weapons/chainwhip.png',
  WeaponsClaws: 'weapons/claws.png',
  WeaponsClub: 'weapons/club.png',
  WeaponsCrossbow: 'weapons/crossbow.png',
  WeaponsHammer: 'weapons/hammer.png',
  WeaponsKnuckles: 'weapons/knuckles.png',
  WeaponsMagicBook: 'weapons/magicbook.png',
  WeaponsMagicStaff: 'weapons/magicstaff.png',
  WeaponsMagicStrike: 'weapons/magicstrike.png',
  WeaponsMusket: 'weapons/musket.png',
  WeaponsRevolver: 'weapons/revolver.png',
  WeaponsRifle: 'weapons/rifle.png',
  WeaponsRope: 'weapons/rope.png',
  WeaponsSlingshot: 'weapons/slingshot.png',
  WeaponsSpear: 'weapons/spear.png',
  WeaponsStaff: 'weapons/staff.png',
  WeaponsStaff2: 'weapons/staff2.png',
  WeaponsWhip: 'weapons/whip.png',
} as const;

export const SodaIconAssetPacks: ReadonlyArray<{
  key: string;
  imagePath: string;
  atlasPath: string;
}> = [
  {
    key: SodaIconAtlases.SodaIcons,
    imagePath: 'assets/atlases/soda-icons.png',
    atlasPath: 'assets/atlases/soda-icons.atlas.json',
  },
];
