export const TinySwordsAtlases = {
  Buildings: 'tiny-swords-buildings',
  UICore: 'tiny-swords-ui-core',
  Resources: 'tiny-swords-resources',
  Portraits: 'tiny-swords-portraits',
  UIPanels: 'tiny-swords-ui-panels',
} as const;

export const TinySwordsBuildingFrames = {
  BlackArchery: 'building/black/archery.png',
  BlackBarracks: 'building/black/barracks.png',
  BlackCastle: 'building/black/castle.png',
  BlackHouse1: 'building/black/house1.png',
  BlackHouse2: 'building/black/house2.png',
  BlackHouse3: 'building/black/house3.png',
  BlackMonastery: 'building/black/monastery.png',
  BlackTower: 'building/black/tower.png',
  BlueArchery: 'building/blue/archery.png',
  BlueBarracks: 'building/blue/barracks.png',
  BlueCastle: 'building/blue/castle.png',
  BlueHouse1: 'building/blue/house1.png',
  BlueHouse2: 'building/blue/house2.png',
  BlueHouse3: 'building/blue/house3.png',
  BlueMonastery: 'building/blue/monastery.png',
  BlueTower: 'building/blue/tower.png',
  PurpleArchery: 'building/purple/archery.png',
  PurpleBarracks: 'building/purple/barracks.png',
  PurpleCastle: 'building/purple/castle.png',
  PurpleHouse1: 'building/purple/house1.png',
  PurpleHouse2: 'building/purple/house2.png',
  PurpleHouse3: 'building/purple/house3.png',
  PurpleMonastery: 'building/purple/monastery.png',
  PurpleTower: 'building/purple/tower.png',
  RedArchery: 'building/red/archery.png',
  RedBarracks: 'building/red/barracks.png',
  RedCastle: 'building/red/castle.png',
  RedHouse1: 'building/red/house1.png',
  RedHouse2: 'building/red/house2.png',
  RedHouse3: 'building/red/house3.png',
  RedMonastery: 'building/red/monastery.png',
  RedTower: 'building/red/tower.png',
  YellowArchery: 'building/yellow/archery.png',
  YellowBarracks: 'building/yellow/barracks.png',
  YellowCastle: 'building/yellow/castle.png',
  YellowHouse1: 'building/yellow/house1.png',
  YellowHouse2: 'building/yellow/house2.png',
  YellowHouse3: 'building/yellow/house3.png',
  YellowMonastery: 'building/yellow/monastery.png',
  YellowTower: 'building/yellow/tower.png',
} as const;

export const TinySwordsUIFrames = {
  Banner: 'ui/banner.png',
  BannerSlots: 'ui/banner-slots.png',
  BigBarBase: 'ui/bigbar-base.png',
  BigBarFill: 'ui/bigbar-fill.png',
  SmallBarBase: 'ui/smallbar-base.png',
  SmallBarFill: 'ui/smallbar-fill.png',
  ButtonBigBluePressed: 'ui/button-bigblue-pressed.png',
  ButtonBigBlueRegular: 'ui/button-bigblue-regular.png',
  ButtonBigRedPressed: 'ui/button-bigred-pressed.png',
  ButtonBigRedRegular: 'ui/button-bigred-regular.png',
  ButtonSmallBlueRoundPressed: 'ui/button-smallblueround-pressed.png',
  ButtonSmallBlueRoundRegular: 'ui/button-smallblueround-regular.png',
  ButtonSmallBlueSquarePressed: 'ui/button-smallbluesquare-pressed.png',
  ButtonSmallBlueSquareRegular: 'ui/button-smallbluesquare-regular.png',
  ButtonSmallRedRoundPressed: 'ui/button-smallredround-pressed.png',
  ButtonSmallRedRoundRegular: 'ui/button-smallredround-regular.png',
  ButtonSmallRedSquarePressed: 'ui/button-smallredsquare-pressed.png',
  ButtonSmallRedSquareRegular: 'ui/button-smallredsquare-regular.png',
  ButtonTinyRoundBlue: 'ui/button-tinyround-blue.png',
  ButtonTinyRoundRed: 'ui/button-tinyround-red.png',
  ButtonTinySquareBlue: 'ui/button-tinysquare-blue.png',
  ButtonTinySquareRed: 'ui/button-tinysquare-red.png',
  Cursor01: 'ui/cursor-01.png',
  Cursor02: 'ui/cursor-02.png',
  Cursor03: 'ui/cursor-03.png',
  Cursor04: 'ui/cursor-04.png',
  Icon01: 'ui/icon-01.png',
  Icon02: 'ui/icon-02.png',
  Icon03: 'ui/icon-03.png',
  Icon04: 'ui/icon-04.png',
  Icon05: 'ui/icon-05.png',
  Icon06: 'ui/icon-06.png',
  Icon07: 'ui/icon-07.png',
  Icon08: 'ui/icon-08.png',
  Icon09: 'ui/icon-09.png',
  Icon10: 'ui/icon-10.png',
  Icon11: 'ui/icon-11.png',
  Icon12: 'ui/icon-12.png',
  PaperRegular: 'ui/paper-regular.png',
  PaperSpecial: 'ui/paper-special.png',
  RibbonsSmall: 'ui/ribbons-small.png',
  Swords: 'ui/swords.png',
  TableWood: 'ui/table-wood.png',
  TableWoodSlots: 'ui/table-wood-slots.png',
} as const;

export const TinySwordsResourceFrames = {
  Gold: 'resource/gold.png',
  GoldStone1: 'resource/gold-stone-1.png',
  GoldStone2: 'resource/gold-stone-2.png',
  GoldStone3: 'resource/gold-stone-3.png',
  GoldStone4: 'resource/gold-stone-4.png',
  GoldStone5: 'resource/gold-stone-5.png',
  GoldStone6: 'resource/gold-stone-6.png',
  Meat: 'resource/meat.png',
  Wood: 'resource/wood.png',
  Tool01: 'resource/tool-01.png',
  Tool02: 'resource/tool-02.png',
  Tool03: 'resource/tool-03.png',
  Tool04: 'resource/tool-04.png',
  Rock1: 'resource/rock-1.png',
  Rock2: 'resource/rock-2.png',
  Rock3: 'resource/rock-3.png',
  Rock4: 'resource/rock-4.png',
  Stump1: 'resource/stump-1.png',
  Stump2: 'resource/stump-2.png',
  Stump3: 'resource/stump-3.png',
  Stump4: 'resource/stump-4.png',
} as const;

export const TinySwordsPortraitFrames = {
  Avatar01: 'portrait/human/avatar-01.png',
  Avatar02: 'portrait/human/avatar-02.png',
  Avatar03: 'portrait/human/avatar-03.png',
  Avatar04: 'portrait/human/avatar-04.png',
  Avatar05: 'portrait/human/avatar-05.png',
  Avatar06: 'portrait/human/avatar-06.png',
  Avatar07: 'portrait/human/avatar-07.png',
  Avatar08: 'portrait/human/avatar-08.png',
  Avatar09: 'portrait/human/avatar-09.png',
  Avatar10: 'portrait/human/avatar-10.png',
  Avatar11: 'portrait/human/avatar-11.png',
  Avatar12: 'portrait/human/avatar-12.png',
  Avatar13: 'portrait/human/avatar-13.png',
  Avatar14: 'portrait/human/avatar-14.png',
  Avatar15: 'portrait/human/avatar-15.png',
  Avatar16: 'portrait/human/avatar-16.png',
  Avatar17: 'portrait/human/avatar-17.png',
  Avatar18: 'portrait/human/avatar-18.png',
  Avatar19: 'portrait/human/avatar-19.png',
  Avatar20: 'portrait/human/avatar-20.png',
  Avatar21: 'portrait/human/avatar-21.png',
  Avatar22: 'portrait/human/avatar-22.png',
  Avatar23: 'portrait/human/avatar-23.png',
  Avatar24: 'portrait/human/avatar-24.png',
  Avatar25: 'portrait/human/avatar-25.png',
} as const;

export const TinySwordsUIPanelFrames = {
  BigRibbons: 'ui-panels/bigribbons.png',
  RibbonBlack: 'ui-panels/ribbon-black.png',
  RibbonBlue: 'ui-panels/ribbon-blue.png',
  RibbonPurple: 'ui-panels/ribbon-purple.png',
  RibbonRed: 'ui-panels/ribbon-red.png',
  RibbonYellow: 'ui-panels/ribbon-yellow.png',
  StoreBanner: 'ui-panels/store-banner.png',
  StoreSlots: 'ui-panels/store-slots.png',
} as const;

export const TinySwordsSpritesheets = {
  UnitBlueWarriorIdle: 'unit-blue-warrior-idle',
  UnitBlueWarriorRun: 'unit-blue-warrior-run',
  UnitBlueWarriorAttack1: 'unit-blue-warrior-attack1',
  UnitBlueArcherIdle: 'unit-blue-archer-idle',
  UnitBlueArcherRun: 'unit-blue-archer-run',
  UnitBlueArcherShoot: 'unit-blue-archer-shoot',
  UnitBluePawnIdle: 'unit-blue-pawn-idle',
  UnitBluePawnRun: 'unit-blue-pawn-run',
  UnitRedWarriorIdle: 'unit-red-warrior-idle',
  UnitRedWarriorRun: 'unit-red-warrior-run',
  UnitRedWarriorAttack1: 'unit-red-warrior-attack1',
  UnitRedArcherIdle: 'unit-red-archer-idle',
  UnitRedArcherRun: 'unit-red-archer-run',
  UnitRedArcherShoot: 'unit-red-archer-shoot',
  UnitRedPawnIdle: 'unit-red-pawn-idle',
  UnitRedPawnRun: 'unit-red-pawn-run',
  ParticleFire01: 'particle-fire-01',
  ParticleDust01: 'particle-dust-01',
  ParticleExplosion01: 'particle-explosion-01',
} as const;

export const TinySwordsTilesets = {
  TerrainColor1: 'terrain-tilemap-color1',
  TerrainColor2: 'terrain-tilemap-color2',
  TerrainShadow: 'terrain-shadow',
  WaterBackground: 'terrain-water-background',
} as const;

export const TinySwordsAssetPacks: ReadonlyArray<{
  key: string;
  imagePath: string;
  atlasPath: string;
}> = [
  {
    key: TinySwordsAtlases.Buildings,
    imagePath: 'assets/atlases/tiny-swords-buildings.png',
    atlasPath: 'assets/atlases/tiny-swords-buildings.atlas.json',
  },
  {
    key: TinySwordsAtlases.UICore,
    imagePath: 'assets/atlases/tiny-swords-ui-core.png',
    atlasPath: 'assets/atlases/tiny-swords-ui-core.atlas.json',
  },
  {
    key: TinySwordsAtlases.Resources,
    imagePath: 'assets/atlases/tiny-swords-resources.png',
    atlasPath: 'assets/atlases/tiny-swords-resources.atlas.json',
  },
  {
    key: TinySwordsAtlases.Portraits,
    imagePath: 'assets/atlases/tiny-swords-portraits.png',
    atlasPath: 'assets/atlases/tiny-swords-portraits.atlas.json',
  },
  {
    key: TinySwordsAtlases.UIPanels,
    imagePath: 'assets/atlases/tiny-swords-ui-panels.png',
    atlasPath: 'assets/atlases/tiny-swords-ui-panels.atlas.json',
  },
];
