export const TinySwordsAtlases = {
  Buildings: 'tiny-swords-buildings',
  UICore: 'tiny-swords-ui-core',
  Resources: 'tiny-swords-resources',
  Portraits: 'tiny-swords-portraits',
  UIPanels: 'tiny-swords-ui-panels',
} as const;

export const TinySwordsBuildingFrames = {
  BlackArchery: 'building/black/archery.png',
  BlackBarracks: 'building/black/barracks.png',
  BlackCastle: 'building/black/castle.png',
  BlackHouse1: 'building/black/house1.png',
  BlackHouse2: 'building/black/house2.png',
  BlackHouse3: 'building/black/house3.png',
  BlackMonastery: 'building/black/monastery.png',
  BlackTower: 'building/black/tower.png',
  BlueArchery: 'building/blue/archery.png',
  BlueBarracks: 'building/blue/barracks.png',
  BlueCastle: 'building/blue/castle.png',
  BlueHouse1: 'building/blue/house1.png',
  BlueHouse2: 'building/blue/house2.png',
  BlueHouse3: 'building/blue/house3.png',
  BlueMonastery: 'building/blue/monastery.png',
  BlueTower: 'building/blue/tower.png',
  PurpleArchery: 'building/purple/archery.png',
  PurpleBarracks: 'building/purple/barracks.png',
  PurpleCastle: 'building/purple/castle.png',
  PurpleHouse1: 'building/purple/house1.png',
  PurpleHouse2: 'building/purple/house2.png',
  PurpleHouse3: 'building/purple/house3.png',
  PurpleMonastery: 'building/purple/monastery.png',
  PurpleTower: 'building/purple/tower.png',
  RedArchery: 'building/red/archery.png',
  RedBarracks: 'building/red/barracks.png',
  RedCastle: 'building/red/castle.png',
  RedHouse1: 'building/red/house1.png',
  RedHouse2: 'building/red/house2.png',
  RedHouse3: 'building/red/house3.png',
  RedMonastery: 'building/red/monastery.png',
  RedTower: 'building/red/tower.png',
  YellowArchery: 'building/yellow/archery.png',
  YellowBarracks: 'building/yellow/barracks.png',
  YellowCastle: 'building/yellow/castle.png',
  YellowHouse1: 'building/yellow/house1.png',
  YellowHouse2: 'building/yellow/house2.png',
  YellowHouse3: 'building/yellow/house3.png',
  YellowMonastery: 'building/yellow/monastery.png',
  YellowTower: 'building/yellow/tower.png',
} as const;

export const TinySwordsUIFrames = {
  Banner: 'ui/banner.png',
  BannerSlots: 'ui/banner-slots.png',
  BigBarBase: 'ui/bigbar-base.png',
  BigBarFill: 'ui/bigbar-fill.png',
  SmallBarBase: 'ui/smallbar-base.png',
  SmallBarFill: 'ui/smallbar-fill.png',
  ButtonBigBluePressed: 'ui/button-bigblue-pressed.png',
  ButtonBigBlueRegular: 'ui/button-bigblue-regular.png',
  ButtonBigRedPressed: 'ui/button-bigred-pressed.png',
  ButtonBigRedRegular: 'ui/button-bigred-regular.png',
  ButtonSmallBlueRoundPressed: 'ui/button-smallblueround-pressed.png',
  ButtonSmallBlueRoundRegular: 'ui/button-smallblueround-regular.png',
  ButtonSmallBlueSquarePressed: 'ui/button-smallbluesquare-pressed.png',
  ButtonSmallBlueSquareRegular: 'ui/button-smallbluesquare-regular.png',
  ButtonSmallRedRoundPressed: 'ui/button-smallredround-pressed.png',
  ButtonSmallRedRoundRegular: 'ui/button-smallredround-regular.png',
  ButtonSmallRedSquarePressed: 'ui/button-smallredsquare-pressed.png',
  ButtonSmallRedSquareRegular: 'ui/button-smallredsquare-regular.png',
  ButtonTinyRoundBlue: 'ui/button-tinyround-blue.png',
  ButtonTinyRoundRed: 'ui/button-tinyround-red.png',
  ButtonTinySquareBlue: 'ui/button-tinysquare-blue.png',
  ButtonTinySquareRed: 'ui/button-tinysquare-red.png',
  Cursor01: 'ui/cursor-01.png',
  Cursor02: 'ui/cursor-02.png',
  Cursor03: 'ui/cursor-03.png',
  Cursor04: 'ui/cursor-04.png',
  Icon01: 'ui/icon-01.png',
  Icon02: 'ui/icon-02.png',
  Icon03: 'ui/icon-03.png',
  Icon04: 'ui/icon-04.png',
  Icon05: 'ui/icon-05.png',
  Icon06: 'ui/icon-06.png',
  Icon07: 'ui/icon-07.png',
  Icon08: 'ui/icon-08.png',
  Icon09: 'ui/icon-09.png',
  Icon10: 'ui/icon-10.png',
  Icon11: 'ui/icon-11.png',
  Icon12: 'ui/icon-12.png',
  PaperRegular: 'ui/paper-regular.png',
  PaperSpecial: 'ui/paper-special.png',
  RibbonsSmall: 'ui/ribbons-small.png',
  Swords: 'ui/swords.png',
  TableWood: 'ui/table-wood.png',
  TableWoodSlots: 'ui/table-wood-slots.png',
} as const;

export const TinySwordsResourceFrames = {
  Gold: 'resource/gold.png',
  GoldStone1: 'resource/gold-stone-1.png',
  GoldStone2: 'resource/gold-stone-2.png',
  GoldStone3: 'resource/gold-stone-3.png',
  GoldStone4: 'resource/gold-stone-4.png',
  GoldStone5: 'resource/gold-stone-5.png',
  GoldStone6: 'resource/gold-stone-6.png',
  Meat: 'resource/meat.png',
  Wood: 'resource/wood.png',
  Tool01: 'resource/tool-01.png',
  Tool02: 'resource/tool-02.png',
  Tool03: 'resource/tool-03.png',
  Tool04: 'resource/tool-04.png',
  Rock1: 'resource/rock-1.png',
  Rock2: 'resource/rock-2.png',
  Rock3: 'resource/rock-3.png',
  Rock4: 'resource/rock-4.png',
  Stump1: 'resource/stump-1.png',
  Stump2: 'resource/stump-2.png',
  Stump3: 'resource/stump-3.png',
  Stump4: 'resource/stump-4.png',
} as const;

export const TinySwordsPortraitFrames = {
  Avatar01: 'portrait/human/avatar-01.png',
  Avatar02: 'portrait/human/avatar-02.png',
  Avatar03: 'portrait/human/avatar-03.png',
  Avatar04: 'portrait/human/avatar-04.png',
  Avatar05: 'portrait/human/avatar-05.png',
  Avatar06: 'portrait/human/avatar-06.png',
  Avatar07: 'portrait/human/avatar-07.png',
  Avatar08: 'portrait/human/avatar-08.png',
  Avatar09: 'portrait/human/avatar-09.png',
  Avatar10: 'portrait/human/avatar-10.png',
  Avatar11: 'portrait/human/avatar-11.png',
  Avatar12: 'portrait/human/avatar-12.png',
  Avatar13: 'portrait/human/avatar-13.png',
  Avatar14: 'portrait/human/avatar-14.png',
  Avatar15: 'portrait/human/avatar-15.png',
  Avatar16: 'portrait/human/avatar-16.png',
  Avatar17: 'portrait/human/avatar-17.png',
  Avatar18: 'portrait/human/avatar-18.png',
  Avatar19: 'portrait/human/avatar-19.png',
  Avatar20: 'portrait/human/avatar-20.png',
  Avatar21: 'portrait/human/avatar-21.png',
  Avatar22: 'portrait/human/avatar-22.png',
  Avatar23: 'portrait/human/avatar-23.png',
  Avatar24: 'portrait/human/avatar-24.png',
  Avatar25: 'portrait/human/avatar-25.png',
} as const;

export const TinySwordsUIPanelFrames = {
  BigRibbons: 'ui-panels/bigribbons.png',
  RibbonBlack: 'ui-panels/ribbon-black.png',
  RibbonBlue: 'ui-panels/ribbon-blue.png',
  RibbonPurple: 'ui-panels/ribbon-purple.png',
  RibbonRed: 'ui-panels/ribbon-red.png',
  RibbonYellow: 'ui-panels/ribbon-yellow.png',
  StoreBanner: 'ui-panels/store-banner.png',
  StoreSlots: 'ui-panels/store-slots.png',
} as const;

export const TinySwordsSpritesheets = {
  // Blue allies
  UnitBlueWarriorIdle: 'unit-blue-warrior-idle',
  UnitBlueWarriorRun: 'unit-blue-warrior-run',
  UnitBlueWarriorAttack1: 'unit-blue-warrior-attack1',
  UnitBlueWarriorAttack2: 'unit-blue-warrior-attack2',
  UnitBlueWarriorGuard: 'unit-blue-warrior-guard',
  UnitBlueArcherIdle: 'unit-blue-archer-idle',
  UnitBlueArcherRun: 'unit-blue-archer-run',
  UnitBlueArcherShoot: 'unit-blue-archer-shoot',
  UnitBlueArcherArrow: 'unit-blue-archer-arrow',
  UnitBlueLancerIdle: 'unit-blue-lancer-idle',
  UnitBlueLancerRun: 'unit-blue-lancer-run',
  UnitBlueLancerRightAttack: 'unit-blue-lancer-right-attack',
  UnitBlueLancerDownAttack: 'unit-blue-lancer-down-attack',
  UnitBlueLancerUpAttack: 'unit-blue-lancer-up-attack',
  UnitBlueLancerDownDefence: 'unit-blue-lancer-down-defence',
  UnitBlueLancerDownRightDefence: 'unit-blue-lancer-downright-defence',
  UnitBlueLancerRightDefence: 'unit-blue-lancer-right-defence',
  UnitBlueLancerUpRightDefence: 'unit-blue-lancer-upright-defence',
  UnitBlueLancerUpDefence: 'unit-blue-lancer-up-defence',
  UnitBlueMonkIdle: 'unit-blue-monk-idle',
  UnitBlueMonkRun: 'unit-blue-monk-run',
  UnitBlueMonkHeal: 'unit-blue-monk-heal',
  UnitBlueMonkHealEffect: 'unit-blue-monk-heal-effect',
  UnitBluePawnIdle: 'unit-blue-pawn-idle',
  UnitBluePawnRun: 'unit-blue-pawn-run',
  // Red enemies
  UnitRedWarriorIdle: 'unit-red-warrior-idle',
  UnitRedWarriorRun: 'unit-red-warrior-run',
  UnitRedWarriorAttack1: 'unit-red-warrior-attack1',
  UnitRedWarriorAttack2: 'unit-red-warrior-attack2',
  UnitRedWarriorGuard: 'unit-red-warrior-guard',
  UnitRedArcherIdle: 'unit-red-archer-idle',
  UnitRedArcherRun: 'unit-red-archer-run',
  UnitRedArcherShoot: 'unit-red-archer-shoot',
  UnitRedArcherArrow: 'unit-red-archer-arrow',
  UnitRedLancerIdle: 'unit-red-lancer-idle',
  UnitRedLancerRun: 'unit-red-lancer-run',
  UnitRedLancerRightAttack: 'unit-red-lancer-right-attack',
  UnitRedLancerDownAttack: 'unit-red-lancer-down-attack',
  UnitRedLancerUpAttack: 'unit-red-lancer-up-attack',
  UnitRedLancerDownDefence: 'unit-red-lancer-down-defence',
  UnitRedLancerDownRightDefence: 'unit-red-lancer-downright-defence',
  UnitRedLancerRightDefence: 'unit-red-lancer-right-defence',
  UnitRedLancerUpRightDefence: 'unit-red-lancer-upright-defence',
  UnitRedLancerUpDefence: 'unit-red-lancer-up-defence',
  UnitRedMonkIdle: 'unit-red-monk-idle',
  UnitRedMonkRun: 'unit-red-monk-run',
  UnitRedMonkHeal: 'unit-red-monk-heal',
  UnitRedMonkHealEffect: 'unit-red-monk-heal-effect',
  UnitRedPawnIdle: 'unit-red-pawn-idle',
  UnitRedPawnRun: 'unit-red-pawn-run',
  // Black faction
  UnitBlackWarriorIdle: 'unit-black-warrior-idle',
  UnitBlackWarriorRun: 'unit-black-warrior-run',
  UnitBlackWarriorAttack1: 'unit-black-warrior-attack1',
  UnitBlackWarriorAttack2: 'unit-black-warrior-attack2',
  UnitBlackWarriorGuard: 'unit-black-warrior-guard',
  UnitBlackArcherIdle: 'unit-black-archer-idle',
  UnitBlackArcherRun: 'unit-black-archer-run',
  UnitBlackArcherShoot: 'unit-black-archer-shoot',
  UnitBlackArcherArrow: 'unit-black-archer-arrow',
  UnitBlackLancerIdle: 'unit-black-lancer-idle',
  UnitBlackLancerRun: 'unit-black-lancer-run',
  UnitBlackLancerRightAttack: 'unit-black-lancer-right-attack',
  UnitBlackLancerDownAttack: 'unit-black-lancer-down-attack',
  UnitBlackLancerUpAttack: 'unit-black-lancer-up-attack',
  UnitBlackLancerDownDefence: 'unit-black-lancer-down-defence',
  UnitBlackLancerDownRightDefence: 'unit-black-lancer-downright-defence',
  UnitBlackLancerRightDefence: 'unit-black-lancer-right-defence',
  UnitBlackLancerUpRightDefence: 'unit-black-lancer-upright-defence',
  UnitBlackLancerUpDefence: 'unit-black-lancer-up-defence',
  UnitBlackMonkIdle: 'unit-black-monk-idle',
  UnitBlackMonkRun: 'unit-black-monk-run',
  UnitBlackMonkHeal: 'unit-black-monk-heal',
  UnitBlackMonkHealEffect: 'unit-black-monk-heal-effect',
  UnitBlackPawnIdle: 'unit-black-pawn-idle',
  UnitBlackPawnRun: 'unit-black-pawn-run',
  // Purple faction
  UnitPurpleWarriorIdle: 'unit-purple-warrior-idle',
  UnitPurpleWarriorRun: 'unit-purple-warrior-run',
  UnitPurpleWarriorAttack1: 'unit-purple-warrior-attack1',
  UnitPurpleWarriorAttack2: 'unit-purple-warrior-attack2',
  UnitPurpleWarriorGuard: 'unit-purple-warrior-guard',
  UnitPurpleArcherIdle: 'unit-purple-archer-idle',
  UnitPurpleArcherRun: 'unit-purple-archer-run',
  UnitPurpleArcherShoot: 'unit-purple-archer-shoot',
  UnitPurpleArcherArrow: 'unit-purple-archer-arrow',
  UnitPurpleLancerIdle: 'unit-purple-lancer-idle',
  UnitPurpleLancerRun: 'unit-purple-lancer-run',
  UnitPurpleLancerRightAttack: 'unit-purple-lancer-right-attack',
  UnitPurpleLancerDownAttack: 'unit-purple-lancer-down-attack',
  UnitPurpleLancerUpAttack: 'unit-purple-lancer-up-attack',
  UnitPurpleLancerDownDefence: 'unit-purple-lancer-down-defence',
  UnitPurpleLancerDownRightDefence: 'unit-purple-lancer-downright-defence',
  UnitPurpleLancerRightDefence: 'unit-purple-lancer-right-defence',
  UnitPurpleLancerUpRightDefence: 'unit-purple-lancer-upright-defence',
  UnitPurpleLancerUpDefence: 'unit-purple-lancer-up-defence',
  UnitPurpleMonkIdle: 'unit-purple-monk-idle',
  UnitPurpleMonkRun: 'unit-purple-monk-run',
  UnitPurpleMonkHeal: 'unit-purple-monk-heal',
  UnitPurpleMonkHealEffect: 'unit-purple-monk-heal-effect',
  UnitPurplePawnIdle: 'unit-purple-pawn-idle',
  UnitPurplePawnRun: 'unit-purple-pawn-run',
  // Yellow faction
  UnitYellowWarriorIdle: 'unit-yellow-warrior-idle',
  UnitYellowWarriorRun: 'unit-yellow-warrior-run',
  UnitYellowWarriorAttack1: 'unit-yellow-warrior-attack1',
  UnitYellowWarriorAttack2: 'unit-yellow-warrior-attack2',
  UnitYellowWarriorGuard: 'unit-yellow-warrior-guard',
  UnitYellowArcherIdle: 'unit-yellow-archer-idle',
  UnitYellowArcherRun: 'unit-yellow-archer-run',
  UnitYellowArcherShoot: 'unit-yellow-archer-shoot',
  UnitYellowArcherArrow: 'unit-yellow-archer-arrow',
  UnitYellowLancerIdle: 'unit-yellow-lancer-idle',
  UnitYellowLancerRun: 'unit-yellow-lancer-run',
  UnitYellowLancerRightAttack: 'unit-yellow-lancer-right-attack',
  UnitYellowLancerDownAttack: 'unit-yellow-lancer-down-attack',
  UnitYellowLancerUpAttack: 'unit-yellow-lancer-up-attack',
  UnitYellowLancerDownDefence: 'unit-yellow-lancer-down-defence',
  UnitYellowLancerDownRightDefence: 'unit-yellow-lancer-downright-defence',
  UnitYellowLancerRightDefence: 'unit-yellow-lancer-right-defence',
  UnitYellowLancerUpRightDefence: 'unit-yellow-lancer-upright-defence',
  UnitYellowLancerUpDefence: 'unit-yellow-lancer-up-defence',
  UnitYellowMonkIdle: 'unit-yellow-monk-idle',
  UnitYellowMonkRun: 'unit-yellow-monk-run',
  UnitYellowMonkHeal: 'unit-yellow-monk-heal',
  UnitYellowMonkHealEffect: 'unit-yellow-monk-heal-effect',
  UnitYellowPawnIdle: 'unit-yellow-pawn-idle',
  UnitYellowPawnRun: 'unit-yellow-pawn-run',
  // Pawn tool variants
  UnitBluePawnIdleAxe: 'unit-blue-pawn-idle-axe',
  UnitBluePawnIdleHammer: 'unit-blue-pawn-idle-hammer',
  UnitBluePawnIdlePickaxe: 'unit-blue-pawn-idle-pickaxe',
  UnitBluePawnIdleGold: 'unit-blue-pawn-idle-gold',
  UnitBluePawnIdleWood: 'unit-blue-pawn-idle-wood',
  UnitBluePawnIdleMeat: 'unit-blue-pawn-idle-meat',
  UnitBluePawnIdleKnife: 'unit-blue-pawn-idle-knife',
  UnitBluePawnRunAxe: 'unit-blue-pawn-run-axe',
  UnitBluePawnRunHammer: 'unit-blue-pawn-run-hammer',
  UnitBluePawnRunPickaxe: 'unit-blue-pawn-run-pickaxe',
  UnitBluePawnRunGold: 'unit-blue-pawn-run-gold',
  UnitBluePawnRunWood: 'unit-blue-pawn-run-wood',
  UnitBluePawnRunMeat: 'unit-blue-pawn-run-meat',
  UnitBluePawnRunKnife: 'unit-blue-pawn-run-knife',
  UnitBluePawnInteractAxe: 'unit-blue-pawn-interact-axe',
  UnitBluePawnInteractHammer: 'unit-blue-pawn-interact-hammer',
  UnitBluePawnInteractPickaxe: 'unit-blue-pawn-interact-pickaxe',
  UnitBluePawnInteractKnife: 'unit-blue-pawn-interact-knife',
  // Red pawn tools
  UnitRedPawnIdleAxe: 'unit-red-pawn-idle-axe',
  UnitRedPawnIdleHammer: 'unit-red-pawn-idle-hammer',
  UnitRedPawnIdlePickaxe: 'unit-red-pawn-idle-pickaxe',
  UnitRedPawnIdleGold: 'unit-red-pawn-idle-gold',
  UnitRedPawnIdleWood: 'unit-red-pawn-idle-wood',
  UnitRedPawnIdleMeat: 'unit-red-pawn-idle-meat',
  UnitRedPawnIdleKnife: 'unit-red-pawn-idle-knife',
  UnitRedPawnRunAxe: 'unit-red-pawn-run-axe',
  UnitRedPawnRunHammer: 'unit-red-pawn-run-hammer',
  UnitRedPawnRunPickaxe: 'unit-red-pawn-run-pickaxe',
  UnitRedPawnRunGold: 'unit-red-pawn-run-gold',
  UnitRedPawnRunWood: 'unit-red-pawn-run-wood',
  UnitRedPawnRunMeat: 'unit-red-pawn-run-meat',
  UnitRedPawnRunKnife: 'unit-red-pawn-run-knife',
  UnitRedPawnInteractAxe: 'unit-red-pawn-interact-axe',
  UnitRedPawnInteractHammer: 'unit-red-pawn-interact-hammer',
  UnitRedPawnInteractPickaxe: 'unit-red-pawn-interact-pickaxe',
  UnitRedPawnInteractKnife: 'unit-red-pawn-interact-knife',
  // Black pawn tools
  UnitBlackPawnIdleAxe: 'unit-black-pawn-idle-axe',
  UnitBlackPawnIdleHammer: 'unit-black-pawn-idle-hammer',
  UnitBlackPawnIdlePickaxe: 'unit-black-pawn-idle-pickaxe',
  UnitBlackPawnIdleGold: 'unit-black-pawn-idle-gold',
  UnitBlackPawnIdleWood: 'unit-black-pawn-idle-wood',
  UnitBlackPawnIdleMeat: 'unit-black-pawn-idle-meat',
  UnitBlackPawnIdleKnife: 'unit-black-pawn-idle-knife',
  UnitBlackPawnRunAxe: 'unit-black-pawn-run-axe',
  UnitBlackPawnRunHammer: 'unit-black-pawn-run-hammer',
  UnitBlackPawnRunPickaxe: 'unit-black-pawn-run-pickaxe',
  UnitBlackPawnRunGold: 'unit-black-pawn-run-gold',
  UnitBlackPawnRunWood: 'unit-black-pawn-run-wood',
  UnitBlackPawnRunMeat: 'unit-black-pawn-run-meat',
  UnitBlackPawnRunKnife: 'unit-black-pawn-run-knife',
  UnitBlackPawnInteractAxe: 'unit-black-pawn-interact-axe',
  UnitBlackPawnInteractHammer: 'unit-black-pawn-interact-hammer',
  UnitBlackPawnInteractPickaxe: 'unit-black-pawn-interact-pickaxe',
  UnitBlackPawnInteractKnife: 'unit-black-pawn-interact-knife',
  // Purple pawn tools
  UnitPurplePawnIdleAxe: 'unit-purple-pawn-idle-axe',
  UnitPurplePawnIdleHammer: 'unit-purple-pawn-idle-hammer',
  UnitPurplePawnIdlePickaxe: 'unit-purple-pawn-idle-pickaxe',
  UnitPurplePawnIdleGold: 'unit-purple-pawn-idle-gold',
  UnitPurplePawnIdleWood: 'unit-purple-pawn-idle-wood',
  UnitPurplePawnIdleMeat: 'unit-purple-pawn-idle-meat',
  UnitPurplePawnIdleKnife: 'unit-purple-pawn-idle-knife',
  UnitPurplePawnRunAxe: 'unit-purple-pawn-run-axe',
  UnitPurplePawnRunHammer: 'unit-purple-pawn-run-hammer',
  UnitPurplePawnRunPickaxe: 'unit-purple-pawn-run-pickaxe',
  UnitPurplePawnRunGold: 'unit-purple-pawn-run-gold',
  UnitPurplePawnRunWood: 'unit-purple-pawn-run-wood',
  UnitPurplePawnRunMeat: 'unit-purple-pawn-run-meat',
  UnitPurplePawnRunKnife: 'unit-purple-pawn-run-knife',
  UnitPurplePawnInteractAxe: 'unit-purple-pawn-interact-axe',
  UnitPurplePawnInteractHammer: 'unit-purple-pawn-interact-hammer',
  UnitPurplePawnInteractPickaxe: 'unit-purple-pawn-interact-pickaxe',
  UnitPurplePawnInteractKnife: 'unit-purple-pawn-interact-knife',
  // Yellow pawn tools
  UnitYellowPawnIdleAxe: 'unit-yellow-pawn-idle-axe',
  UnitYellowPawnIdleHammer: 'unit-yellow-pawn-idle-hammer',
  UnitYellowPawnIdlePickaxe: 'unit-yellow-pawn-idle-pickaxe',
  UnitYellowPawnIdleGold: 'unit-yellow-pawn-idle-gold',
  UnitYellowPawnIdleWood: 'unit-yellow-pawn-idle-wood',
  UnitYellowPawnIdleMeat: 'unit-yellow-pawn-idle-meat',
  UnitYellowPawnIdleKnife: 'unit-yellow-pawn-idle-knife',
  UnitYellowPawnRunAxe: 'unit-yellow-pawn-run-axe',
  UnitYellowPawnRunHammer: 'unit-yellow-pawn-run-hammer',
  UnitYellowPawnRunPickaxe: 'unit-yellow-pawn-run-pickaxe',
  UnitYellowPawnRunGold: 'unit-yellow-pawn-run-gold',
  UnitYellowPawnRunWood: 'unit-yellow-pawn-run-wood',
  UnitYellowPawnRunMeat: 'unit-yellow-pawn-run-meat',
  UnitYellowPawnRunKnife: 'unit-yellow-pawn-run-knife',
  UnitYellowPawnInteractAxe: 'unit-yellow-pawn-interact-axe',
  UnitYellowPawnInteractHammer: 'unit-yellow-pawn-interact-hammer',
  UnitYellowPawnInteractPickaxe: 'unit-yellow-pawn-interact-pickaxe',
  UnitYellowPawnInteractKnife: 'unit-yellow-pawn-interact-knife',
  // Particles
  ParticleFire01: 'particle-fire-01',
  ParticleFire02: 'particle-fire-02',
  ParticleFire03: 'particle-fire-03',
  ParticleDust01: 'particle-dust-01',
  ParticleDust02: 'particle-dust-02',
  ParticleExplosion01: 'particle-explosion-01',
  ParticleExplosion02: 'particle-explosion-02',
  ParticleWaterSplash: 'particle-water-splash',
  // Gold highlight
  GoldResourceHighlight: 'gold-resource-highlight',
  GoldStone1Highlight: 'gold-stone-1-highlight',
  GoldStone2Highlight: 'gold-stone-2-highlight',
  GoldStone3Highlight: 'gold-stone-3-highlight',
  GoldStone4Highlight: 'gold-stone-4-highlight',
  GoldStone5Highlight: 'gold-stone-5-highlight',
  GoldStone6Highlight: 'gold-stone-6-highlight',
} as const;

export const TinySwordsTilesets = {
  TerrainColor1: 'terrain-tilemap-color1',
  TerrainColor2: 'terrain-tilemap-color2',
  TerrainColor3: 'terrain-tilemap-color3',
  TerrainColor4: 'terrain-tilemap-color4',
  TerrainColor5: 'terrain-tilemap-color5',
  TerrainShadow: 'terrain-shadow',
  WaterBackground: 'terrain-water-background',
} as const;

export const TinySwordsArcherArrows: ReadonlyArray<{ key: string; path: string }> = [
  { key: 'unit-blue-archer-arrow', path: 'assets/source/tiny-swords/units/blue-units/archer/arrow.png' },
  { key: 'unit-red-archer-arrow', path: 'assets/source/tiny-swords/units/red-units/archer/arrow.png' },
  { key: 'unit-black-archer-arrow', path: 'assets/source/tiny-swords/units/black-units/archer/arrow.png' },
  { key: 'unit-purple-archer-arrow', path: 'assets/source/tiny-swords/units/purple-units/archer/arrow.png' },
  { key: 'unit-yellow-archer-arrow', path: 'assets/source/tiny-swords/units/yellow-units/archer/arrow.png' },
];

export const TinySwordsAssetPacks: ReadonlyArray<{
  key: string;
  imagePath: string;
  atlasPath: string;
}> = [
  {
    key: TinySwordsAtlases.Buildings,
    imagePath: 'assets/atlases/tiny-swords-buildings.png',
    atlasPath: 'assets/atlases/tiny-swords-buildings.atlas.json',
  },
  {
    key: TinySwordsAtlases.UICore,
    imagePath: 'assets/atlases/tiny-swords-ui-core.png',
    atlasPath: 'assets/atlases/tiny-swords-ui-core.atlas.json',
  },
  {
    key: TinySwordsAtlases.Resources,
    imagePath: 'assets/atlases/tiny-swords-resources.png',
    atlasPath: 'assets/atlases/tiny-swords-resources.atlas.json',
  },
  {
    key: TinySwordsAtlases.Portraits,
    imagePath: 'assets/atlases/tiny-swords-portraits.png',
    atlasPath: 'assets/atlases/tiny-swords-portraits.atlas.json',
  },
  {
    key: TinySwordsAtlases.UIPanels,
    imagePath: 'assets/atlases/tiny-swords-ui-panels.png',
    atlasPath: 'assets/atlases/tiny-swords-ui-panels.atlas.json',
  },
];
